version: '3'

services:
  redpanda:
    image: vectorized/redpanda:v21.11.12
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
      - "9644:9644"
    # networks:
    #   - demo